#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'arrayManipulation' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def arrayManipulation(n, queries):
    # Write your code here
    arr=[0 for i in range(n+1)]
    maxi=0
    
    #We use the concept of prefix sum
    #We consider the arr to be the prefix sum array of
    # the array we need to construct
    #This avoids the loop to add the num between a and b indices
    
    for q in queries:
        i=q[0]-1
        j=q[1]-1
        num=q[2]
        
        #Keen Observation reveals it is true!!    
        arr[i]+=num
        arr[j+1]-=num
    sumi=0
    
    #The sum is nothing but the elemnts of original array we were supposed to create
    for i in arr:
        sumi+=i
        maxi=max(sumi,maxi)
     
    return maxi     

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
